server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://database:3306/pasteme
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver # Java Database Connector
