server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4399/pasteme
    username: username
    password: password

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: cn.pasteme.common.entity

logging:
  file: app.log
  level:
    root: WARN
    org.springfromwork.web: INFO
    cn.pasteme:
      admin: TRACE
      backend: TRACE
      common: TRACE
